/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Bonjour.h
 #	source generated by 4D Plugin Wizard
 #	Project : Bonjour
 #	author : miyako
 #	2020/04/07
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_BONJOUR_H
#define PLUGIN_BONJOUR_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include <mutex>

#include "json/json.h"
#include <sys/socket.h>
#include <arpa/inet.h>

#import <Foundation/Foundation.h>

#pragma mark -

void Bonjour_Publish(PA_PluginParameters params);
void Bonjour_Status(PA_PluginParameters params);
void Bonjour_Discover(PA_PluginParameters params);
void Bonjour_Update(PA_PluginParameters params);
void Bonjour_Clear(PA_PluginParameters params);

void g_bonjour_delegates_clear();

#define DEFAULT_RESOLVE_TIMEOUT 10.0f

#endif /* PLUGIN_BONJOUR_H */
